version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - '81:80'