pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }
    
    stages {
        stage('Download repo') {
            steps {
                script {
                // The below will clone your repo and will be checked out to master branch by default.
                git url: 'https://github.com/Belendor/SocialTimeline.git' // credentialsId: 'belendor',
                // Do a ls -lart to view all the files are cloned. It will be clonned. This is just for you to be sure about it.
                sh "ls -lart ./*" 
                // List all branches in your repo. 
                sh "git branch -a"
                // Checkout to a specific branch in your repo.
                sh "git checkout master"
                }
            }
        }

        stage('Docker compose') {
             steps {
                sh '''
                    sudo docker --version
                    sudo docker compose version
                '''
            }
        }
    }
}